apiVersion: apps/v1
kind: Deployment
metadata:
  name: massage-bot
  labels:
    app: massage-bot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: massage-bot
  template:
    metadata:
      labels:
        app: massage-bot
    spec:
      # ADD THIS: Image pull secret
      imagePullSecrets:
      - name: gitlab-registry
      containers:
      - name: massage-bot
        image: registry.gitlab.com/kfilin/massage-bot:latest
        imagePullPolicy: Always
        # ... rest of your config ...
