apiVersion: v1
kind: Service
metadata:
  name: massage-bot
  namespace: default
  labels:
    app: massage-bot
spec:
  selector:
    app: massage-bot
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP
