services:
  app:
    container_name: massage-bot-test
    environment:
      - HEALTH_PORT=8083
    restart: unless-stopped
    networks:
      massage-bot-internal:
      caddy-test-net:
        aliases:
          - massage-bot-test

  db:
    container_name: massage-bot-db-test
    environment:
      POSTGRES_DB: massage_bot_test

networks:
  caddy-test-net:
    external: true

